### Health check
GET http://127.0.0.1:8004/api/health

###

### Listar pedidos
GET http://127.0.0.1:8004/api/pedidos
Authorization: 21d99b1db05b496722e10c0f51c389c82f136012526f4a07b122126c1f9a9483

###

### Filtrar por estado
GET http://127.0.0.1:8004/api/pedidos?estado=pendiente
Authorization: 21d99b1db05b496722e10c0f51c389c82f136012526f4a07b122126c1f9a9483

###

### Ver pedido por ID
GET http://127.0.0.1:8004/api/pedidos/1
Authorization: 21d99b1db05b496722e10c0f51c389c82f136012526f4a07b122126c1f9a9483

###

### Crear pedido
POST http://127.0.0.1:8004/api/pedidos
Content-Type: application/json

{
    "mesa_id": 1,
    "productos": [
        {
            "producto_id": 1,
            "nombre_producto": "Hamburguesa Especial",
            "cantidad": 2,
            "precio_unitario": 28000
        },
        {
            "producto_id": 2,
            "nombre_producto": "Limonada Natural",
            "cantidad": 2,
            "precio_unitario": 8000
        }
    ]
}

###

### Cambiar a en preparacion
PATCH http://127.0.0.1:8004/api/pedidos/1/estado
Content-Type: application/json

{
    "estado": "en_preparacion"
}

###

### Cambiar a entregado
PATCH http://127.0.0.1:8004/api/pedidos/1/estado
Content-Type: application/json

{
    "estado": "entregado"
}

###

### Cambiar a pagado
PATCH http://127.0.0.1:8004/api/pedidos/1/estado
Content-Type: application/json

{
    "estado": "pagado"
}

###

### Agregar producto al pedido
POST http://127.0.0.1:8004/api/pedidos/1/detalles
Content-Type: application/json

{
    "producto_id": 3,
    "nombre_producto": "Cheesecake",
    "cantidad": 1,
    "precio_unitario": 12000
}

###

### Modificar cantidad de detalle
PUT http://127.0.0.1:8004/api/pedidos/1/detalles/1
Content-Type: application/json

{
    "cantidad": 3
}

###

### Eliminar producto del pedido
DELETE http://127.0.0.1:8004/api/pedidos/1/detalles/1
Authorization: 21d99b1db05b496722e10c0f51c389c82f136012526f4a07b122126c1f9a9483